### PR TITLE
Added a simple heatmap based on retentionHeatmap that can be used for any 2-label data

### PR DESCRIPTION
**Pull request by loufranco**
I based this visualization on the retention heat map, but simplified it so I could use it on my more generic 2-label data.

I don't know what you use to minimize, but I could add a commit with the correct minimizations if you tell me how to do it.

### CODE REVIEW

**Comment by loufranco** [comment]
@leqilong What is the best way to move this PR forward?  I can add the min.js if you tell me how -- I could make any other changes you want.

I'm using this now in a mode report and it would be nice if I could just include it (which requires it to be hosted by mode)

**Comment by leqilong** [comment]
Hi @loufranco, sorry for missing your PR. We use [uglifyjs](https://github.com/mishoo/UglifyJS2) to minimize the alamode.js file. You can use this command to do so:
`uglifyjs --compress --mangle -- alamode.js`

As for the alamode.css file, we use [csso](https://github.com/css/csso). And the command is:
`csso alamode.css --output alamode.min.css
`

**Comment by loufranco** [comment]
Ok @leqilong, I minified.  Let me know if there's anything else I need to do.

**Comment by leqilong** [comment]
@loufranco Thanks. I've deployed your changes. You should be able to start using it now.

**Pull request merged**
